// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockmetricWriter is a mock of metricWriter interface.
type MockmetricWriter struct {
	ctrl     *gomock.Controller
	recorder *MockmetricWriterMockRecorder
}

// MockmetricWriterMockRecorder is the mock recorder for MockmetricWriter.
type MockmetricWriterMockRecorder struct {
	mock *MockmetricWriter
}

// NewMockmetricWriter creates a new mock instance.
func NewMockmetricWriter(ctrl *gomock.Controller) *MockmetricWriter {
	mock := &MockmetricWriter{ctrl: ctrl}
	mock.recorder = &MockmetricWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmetricWriter) EXPECT() *MockmetricWriterMockRecorder {
	return m.recorder
}

// AddMetric mocks base method.
func (m *MockmetricWriter) AddMetric(myType, name, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMetric", myType, name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMetric indicates an expected call of AddMetric.
func (mr *MockmetricWriterMockRecorder) AddMetric(myType, name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMetric", reflect.TypeOf((*MockmetricWriter)(nil).AddMetric), myType, name, value)
}

// BatchUpdateMetrics mocks base method.
func (m *MockmetricWriter) BatchUpdateMetrics(r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateMetrics", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdateMetrics indicates an expected call of BatchUpdateMetrics.
func (mr *MockmetricWriterMockRecorder) BatchUpdateMetrics(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateMetrics", reflect.TypeOf((*MockmetricWriter)(nil).BatchUpdateMetrics), r)
}

// UpdateMetrics mocks base method.
func (m *MockmetricWriter) UpdateMetrics(r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetrics", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetrics indicates an expected call of UpdateMetrics.
func (mr *MockmetricWriterMockRecorder) UpdateMetrics(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetrics", reflect.TypeOf((*MockmetricWriter)(nil).UpdateMetrics), r)
}

// MockmetricReader is a mock of metricReader interface.
type MockmetricReader struct {
	ctrl     *gomock.Controller
	recorder *MockmetricReaderMockRecorder
}

// MockmetricReaderMockRecorder is the mock recorder for MockmetricReader.
type MockmetricReaderMockRecorder struct {
	mock *MockmetricReader
}

// NewMockmetricReader creates a new mock instance.
func NewMockmetricReader(ctrl *gomock.Controller) *MockmetricReader {
	mock := &MockmetricReader{ctrl: ctrl}
	mock.recorder = &MockmetricReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmetricReader) EXPECT() *MockmetricReaderMockRecorder {
	return m.recorder
}

// GetAllMetric mocks base method.
func (m *MockmetricReader) GetAllMetric() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetric")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMetric indicates an expected call of GetAllMetric.
func (mr *MockmetricReaderMockRecorder) GetAllMetric() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetric", reflect.TypeOf((*MockmetricReader)(nil).GetAllMetric))
}

// GetMetrics mocks base method.
func (m *MockmetricReader) GetMetrics(name string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockmetricReaderMockRecorder) GetMetrics(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockmetricReader)(nil).GetMetrics), name)
}

// ValueMetrics mocks base method.
func (m *MockmetricReader) ValueMetrics(r io.Reader) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValueMetrics", r)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValueMetrics indicates an expected call of ValueMetrics.
func (mr *MockmetricReaderMockRecorder) ValueMetrics(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValueMetrics", reflect.TypeOf((*MockmetricReader)(nil).ValueMetrics), r)
}

// Mockconnector is a mock of connector interface.
type Mockconnector struct {
	ctrl     *gomock.Controller
	recorder *MockconnectorMockRecorder
}

// MockconnectorMockRecorder is the mock recorder for Mockconnector.
type MockconnectorMockRecorder struct {
	mock *Mockconnector
}

// NewMockconnector creates a new mock instance.
func NewMockconnector(ctrl *gomock.Controller) *Mockconnector {
	mock := &Mockconnector{ctrl: ctrl}
	mock.recorder = &MockconnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockconnector) EXPECT() *MockconnectorMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *Mockconnector) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockconnectorMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*Mockconnector)(nil).Connect))
}

// Mockstorage is a mock of storage interface.
type Mockstorage struct {
	ctrl     *gomock.Controller
	recorder *MockstorageMockRecorder
}

// MockstorageMockRecorder is the mock recorder for Mockstorage.
type MockstorageMockRecorder struct {
	mock *Mockstorage
}

// NewMockstorage creates a new mock instance.
func NewMockstorage(ctrl *gomock.Controller) *Mockstorage {
	mock := &Mockstorage{ctrl: ctrl}
	mock.recorder = &MockstorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstorage) EXPECT() *MockstorageMockRecorder {
	return m.recorder
}

// AddMetric mocks base method.
func (m *Mockstorage) AddMetric(myType, name, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMetric", myType, name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMetric indicates an expected call of AddMetric.
func (mr *MockstorageMockRecorder) AddMetric(myType, name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMetric", reflect.TypeOf((*Mockstorage)(nil).AddMetric), myType, name, value)
}

// BatchUpdateMetrics mocks base method.
func (m *Mockstorage) BatchUpdateMetrics(r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateMetrics", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdateMetrics indicates an expected call of BatchUpdateMetrics.
func (mr *MockstorageMockRecorder) BatchUpdateMetrics(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateMetrics", reflect.TypeOf((*Mockstorage)(nil).BatchUpdateMetrics), r)
}

// GetAllMetric mocks base method.
func (m *Mockstorage) GetAllMetric() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetric")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMetric indicates an expected call of GetAllMetric.
func (mr *MockstorageMockRecorder) GetAllMetric() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetric", reflect.TypeOf((*Mockstorage)(nil).GetAllMetric))
}

// GetMetrics mocks base method.
func (m *Mockstorage) GetMetrics(name string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockstorageMockRecorder) GetMetrics(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*Mockstorage)(nil).GetMetrics), name)
}

// UpdateMetrics mocks base method.
func (m *Mockstorage) UpdateMetrics(r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetrics", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetrics indicates an expected call of UpdateMetrics.
func (mr *MockstorageMockRecorder) UpdateMetrics(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetrics", reflect.TypeOf((*Mockstorage)(nil).UpdateMetrics), r)
}

// ValueMetrics mocks base method.
func (m *Mockstorage) ValueMetrics(r io.Reader) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValueMetrics", r)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValueMetrics indicates an expected call of ValueMetrics.
func (mr *MockstorageMockRecorder) ValueMetrics(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValueMetrics", reflect.TypeOf((*Mockstorage)(nil).ValueMetrics), r)
}
